[workspace]
members = [ "projects/branches", "projects/chapter3_practise", "projects/functions", "projects/guessing_game",
    "projects/hello_cargo"
, "projects/loops", "projects/variables"]
resolver = "2"
